### ISSUE TITLE
Error while exporting session

### ISSUE THREAD

**Issue by jeromecomte** [exense/djigger#127]
Got following error while exporting a session of type "Attach". At the time of export the capture (Sampling) was not running.
I started and stopped the capture and it worked afterward

Error while running monitored execution
java.util.ConcurrentModificationException: null
        at java.base/java.util.ArrayList.writeObject(ArrayList.java:870) ~[na:na]
        at java.base/jdk.internal.reflect.GeneratedMethodAccessor17.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
        at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1196) ~[na:na]
        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1523) ~[na:na]
        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1444) ~[na:na]
        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187) ~[na:na]
        at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1579) ~[na:na]
        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1536) ~[na:na]
        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1444) ~[na:na]
        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187) ~[na:na]
        at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1579) ~[na:na]
        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1536) ~[na:na]
        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1444) ~[na:na]
        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187) ~[na:na]
        at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1579) ~[na:na]
        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1536) ~[na:na]
        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1444) ~[na:na]
        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187) ~[na:na]
        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:353) ~[na:na]
        at io.djigger.ui.model.SessionExport.normalSave(SessionExport.java:53) ~[client-ui-1.11.2.jar:na]
        at io.djigger.ui.model.SessionExport.save(SessionExport.java:44) ~[client-ui-1.11.2.jar:na]
        at io.djigger.ui.agentcontrol.SessionControlPane$4$1.run(SessionControlPane.java:110) ~[client-ui-1.11.2.jar:na]
        at io.djigger.ui.common.MonitoredExecution$ProgressRunnable.run(MonitoredExecution.java:145) ~[client-ui-1.11.2.jar:na]
        at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]

**Comment by david-stephan** [comment]
Hi, the issue could be reproduced and fixed with this [commit](https://github.com/exense/djigger/commit/381d47485046e0b6ed92412a07c65417059f35ad), the fix will be available with the next minor release 1.11.3.
