### ISSUE TITLE
[Client] FileNotFound when providing complete path to a djigger session

### ISSUE THREAD

**Issue by doriancransac** [exense/djigger#48]
When loading a Saved Session, providing the complete path to the file in the dialog box fails with the following Exception :

```
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: No file has been selected
    at io.djigger.ui.connectiondialog.FileChooserParameters.getSessionConfiguration(FileChooserParameters.java:59)
    at io.djigger.ui.connectiondialog.AgentConnectionDialog.getSessionConfiguration(AgentConnectionDialog.java:128)
    at io.djigger.ui.MainToolbarPane.addSession(MainToolbarPane.java:73)
    at io.djigger.ui.MainToolbarPane$1.run(MainToolbarPane.java:44)
    at io.djigger.ui.common.CommandButton$1.actionPerformed(CommandButton.java:54)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:308)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
    at java.awt.Component.processMouseEvent(Component.java:6516)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
    at java.awt.Component.processEvent(Component.java:6281)
    at java.awt.Container.processEvent(Container.java:2229)
    at java.awt.Component.dispatchEventImpl(Component.java:4872)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Component.dispatchEvent(Component.java:4698)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
    at java.awt.Container.dispatchEventImpl(Container.java:2273)
    at java.awt.Window.dispatchEventImpl(Window.java:2719)
    at java.awt.Component.dispatchEvent(Component.java:4698)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:747)
    at java.awt.EventQueue.access$300(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:706)
    at java.awt.EventQueue$3.run(EventQueue.java:704)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
    at java.awt.EventQueue$4.run(EventQueue.java:720)
    at java.awt.EventQueue$4.run(EventQueue.java:718)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:717)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

```

**Comment by dcransac** [comment]
+ would be cool if we could "cache" i.e remember the last path that the user used to go find their session file. When I open several in a row, and the path is long, it's a pain in the butt, I have to say.

**Comment by jeromecomte** [comment]
This should already be the case. Isn t it working? Do you have write access
to the bin folder where you re starting djigger?
Am 21.04.2016 4:34 Nachm. schrieb "Dorian Cransac" <notifications@github.com

**Comment by dcransac** [comment]
From what I can remember it works for saving but not for loading. I can
check later again though.

**Comment by dcransac** [comment]
Same problem when trying to load the tools.jar file. Also the expected behaviour when providing an incomplete path (path to a folder for instance), is for the system dialog window to CD into that folder instead of disgracefully server an error in the log file.

**Comment by clangguth** [comment]
Does this still happen with #100 applied? 

If so, and if you can provide steps to reproduce this, I'm willing to look into it.

**Comment by david-stephan** [comment]
Issue solved by above mentionned PR.
