### ISSUE TITLE
[Client] Client hangs on retrieval widget (mongo timeout missing at iterator level?)

### ISSUE THREAD

**Issue by doriancransac** [exense/djigger#76]
![image](https://cloud.githubusercontent.com/assets/5418782/16304182/98a2ca34-3954-11e6-99ee-7d09947c002f.png)

"Thread-8" #33 prio=6 os_prio=0 tid=0x000000001ff10000 nid=0x3f38 runnable [0x000000002931e000]
   java.lang.Thread.State: RUNNABLE
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at com.mongodb.connection.SocketStream.read(SocketStream.java:85)
        at com.mongodb.connection.InternalStreamConnection.receiveResponseBuffers(InternalStreamConnection.java:491)
        at com.mongodb.connection.InternalStreamConnection.receiveMessage(InternalStreamConnection.java:221)
        at com.mongodb.connection.UsageTrackingInternalConnection.receiveMessage(UsageTrackingInternalConnection.java:102)
        at com.mongodb.connection.DefaultConnectionPool$PooledConnection.receiveMessage(DefaultConnectionPool.java:435)
        at com.mongodb.connection.CommandProtocol.execute(CommandProtocol.java:112)
        at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:159)
        at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:286)
        at com.mongodb.connection.DefaultServerConnection.command(DefaultServerConnection.java:173)
        at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:215)
        at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:206)
        at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:112)
        at com.mongodb.operation.FindOperation$1.call(FindOperation.java:487)
        at com.mongodb.operation.FindOperation$1.call(FindOperation.java:482)
        at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:239)
        at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:212)
        at com.mongodb.operation.FindOperation.execute(FindOperation.java:482)
        at com.mongodb.operation.FindOperation.execute(FindOperation.java:79)
        at com.mongodb.Mongo.execute(Mongo.java:772)
        at com.mongodb.Mongo$2.execute(Mongo.java:759)
        at com.mongodb.OperationIterable.iterator(OperationIterable.java:47)
        at com.mongodb.FindIterableImpl.iterator(FindIterableImpl.java:143)
        at io.djigger.collector.accessors.stackref.ThreadInfoAccessorImpl$1.iterator(ThreadInfoAccessorImpl.java:104)
        at io.djigger.ui.storebrowser.StoreBrowserPane$3.retrieveThreadInfos(StoreBrowserPane.java:219)
        at io.djigger.ui.storebrowser.StoreBrowserPane$3.run(StoreBrowserPane.java:192)
        at io.djigger.ui.common.MonitoredExecution$ProgressRunnable.run(MonitoredExecution.java:154)
        at java.lang.Thread.run(Unknown Source)

**Comment by david-stephan** [comment]
Issue cannot be reproduced. Please reopen that issue by sharing a dump of your database if the issue is still present in latest djigger version.
